-- Audiobook Brain v1 schema
-- SQLite + sqlite-vec for vector search.
-- Designed to port cleanly to Postgres + pgvector later.

CREATE TABLE IF NOT EXISTS books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  -- Normalized form of title+author used for deduplication.
  -- Generated by the application layer (not a SQLite generated column,
  -- so the same logic ports to Postgres).
  dedupe_key TEXT NOT NULL,

  source_file TEXT,                     -- nullable: manual entries have no file
  chapter_count INTEGER DEFAULT 0,

  -- Library / reading state
  reading_status TEXT NOT NULL DEFAULT 'want_to_read'
    CHECK (reading_status IN ('want_to_read', 'reading', 'finished', 'abandoned')),
  rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  note TEXT,                            -- free-text "what I took from it"
  cover_url TEXT,                       -- from Open Library lookup, optional
  finished_at TEXT,                     -- ISO timestamp; set when status -> finished

  -- Ingestion state
  is_ingested INTEGER NOT NULL DEFAULT 0,    -- 1 if chapters+chunks exist
  current_chapter INTEGER DEFAULT 0,
  ingest_status TEXT DEFAULT 'none'
    CHECK (ingest_status IN ('none', 'processing', 'ready', 'failed')),

  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),

  UNIQUE(dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_books_status ON books(reading_status);
CREATE INDEX IF NOT EXISTS idx_books_finished_at ON books(finished_at);

CREATE TABLE IF NOT EXISTS chapters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  chapter_number INTEGER NOT NULL,
  title TEXT,
  word_count INTEGER,
  extraction TEXT NOT NULL,             -- JSON
  UNIQUE(book_id, chapter_number)
);

CREATE INDEX IF NOT EXISTS idx_chapters_book ON chapters(book_id);

-- Embedded chunks for semantic retrieval.
-- chapter_id is nullable so manual notes (chunk_type='note') can attach
-- to a book without belonging to a chapter.
CREATE TABLE IF NOT EXISTS chunks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
  chapter_id INTEGER REFERENCES chapters(id) ON DELETE CASCADE,
  chapter_number INTEGER,                -- denormalized; null for non-chapter chunks
  chunk_type TEXT NOT NULL CHECK (chunk_type IN (
    'summary', 'claim', 'framework', 'passage', 'connection', 'question', 'note',
    'event', 'character', 'location'
  )),
  content TEXT NOT NULL,
  payload TEXT NOT NULL                  -- JSON
);

CREATE INDEX IF NOT EXISTS idx_chunks_book ON chunks(book_id);
CREATE INDEX IF NOT EXISTS idx_chunks_chapter ON chunks(chapter_id);
