-- BookCompanion production schema for Supabase Postgres.
-- Run in the Supabase SQL editor for the shared MyPlayground project.
--
-- After running this, add `book_companion` to Supabase Dashboard ->
-- Settings -> API -> Exposed schemas so PostgREST can serve these tables/RPCs.

create extension if not exists vector with schema extensions;

create schema if not exists book_companion;

create table if not exists book_companion.books (
  id integer generated by default as identity primary key,
  title text not null,
  author text not null,
  dedupe_key text not null unique,

  source_file text,
  chapter_count integer not null default 0,

  reading_status text not null default 'want_to_read'
    check (reading_status in ('want_to_read', 'reading', 'finished', 'abandoned')),
  rating integer check (rating is null or rating between 1 and 5),
  note text,
  cover_url text,
  finished_at timestamptz,

  is_ingested boolean not null default false,
  current_chapter integer not null default 0,
  ingest_status text not null default 'none'
    check (ingest_status in ('none', 'processing', 'ready', 'failed')),
  book_type text check (book_type in ('fiction', 'nonfiction')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_status_idx on book_companion.books(reading_status);
create index if not exists books_finished_at_idx on book_companion.books(finished_at);

create table if not exists book_companion.chapters (
  id integer generated by default as identity primary key,
  book_id integer not null references book_companion.books(id) on delete cascade,
  chapter_number integer not null,
  title text,
  word_count integer,
  extraction jsonb not null,
  unique(book_id, chapter_number)
);

create index if not exists chapters_book_idx on book_companion.chapters(book_id);

create table if not exists book_companion.chunks (
  id integer generated by default as identity primary key,
  book_id integer not null references book_companion.books(id) on delete cascade,
  chapter_id integer references book_companion.chapters(id) on delete cascade,
  chapter_number integer,
  chunk_type text not null check (chunk_type in (
    'summary', 'claim', 'framework', 'passage', 'connection', 'question', 'note',
    'event', 'character', 'location'
  )),
  content text not null,
  payload jsonb not null
);

create index if not exists chunks_book_idx on book_companion.chunks(book_id);
create index if not exists chunks_chapter_idx on book_companion.chunks(chapter_id);

create table if not exists book_companion.chunk_vectors (
  chunk_id integer primary key references book_companion.chunks(id) on delete cascade,
  embedding vector(512) not null
);

create index if not exists chunk_vectors_embedding_idx
  on book_companion.chunk_vectors
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

alter table book_companion.books enable row level security;
alter table book_companion.chapters enable row level security;
alter table book_companion.chunks enable row level security;
alter table book_companion.chunk_vectors enable row level security;

create or replace function book_companion.match_chunks(
  query_embedding vector(512),
  target_book_id integer,
  match_count integer default 8
)
returns table (
  chunk_type text,
  content text,
  payload jsonb,
  chapter_number integer,
  chapter_title text,
  book_title text,
  book_author text,
  distance double precision
)
language sql
stable
security invoker
set search_path = book_companion, public, extensions
as $$
  select
    c.chunk_type,
    c.content,
    c.payload,
    c.chapter_number,
    ch.title as chapter_title,
    b.title as book_title,
    b.author as book_author,
    (v.embedding <=> query_embedding) as distance
  from chunk_vectors v
  join chunks c on c.id = v.chunk_id
  left join chapters ch on ch.id = c.chapter_id
  join books b on b.id = c.book_id
  where c.book_id = target_book_id
  order by v.embedding <=> query_embedding
  limit match_count;
$$;

grant usage on schema book_companion to service_role;
grant select, insert, update, delete on all tables in schema book_companion to service_role;
grant usage, select on all sequences in schema book_companion to service_role;
grant execute on function book_companion.match_chunks(vector, integer, integer) to service_role;

alter default privileges in schema book_companion
  grant select, insert, update, delete on tables to service_role;

alter default privileges in schema book_companion
  grant usage, select on sequences to service_role;
